### PR TITLE
fix: MagicContext's data reset on restart

### LINKED ISSUE #984: bug: MagicContext resets on restart
### Report

 MagicContext resets on restart, leading to intent_id starting from 0 

### Commit / version

8d4d64cdad591cb4b50c5d40bdf8303a7c276179

### Environment

_No response_

### PR DESCRIPTION
**Pull request by taco-paco**
## Summary
Fixes MagicContext reset on restart.

## Compatibility
- [ ] No breaking changes
- [ ] Config change (describe):
- [ ] Migration needed (describe):

## Testing
- [ ] tests (or explain)

## Checklist
- [ ] docs updated (if needed)
- [ ] closes #984 

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved account initialization logic to prevent duplicate entries.
  * Enhanced error handling for account setup operations.

* **Chores**
  * Optimized resource allocation and default configuration parameters.

### CODE REVIEW

File: magicblock-api/src/fund_account.rs [hunk 1]
```diff
@@ -70,15 +70,24 @@ pub(crate) fn funded_faucet(
 }
 
 pub(crate) fn fund_magic_context(accountsdb: &AccountsDb) {
-    fund_account_with_data(
```
Comment (bmuddha) [inline magicblock-api/src/fund_account.rs]: I think it's better to tweak the fund_account_with_data method to prevent any mutation if account already exists, all use cases assume that anyway.

Comment (taco-paco) [reply magicblock-api/src/fund_account.rs]: If that is the case, then it is better. Do we want to refill lamports for all of them tho?

**Review by bmuddha — APPROVED** [review]

File: magicblock-committor-service/CLAUDE.md [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+
+Delivery strategy is an enum:
+```
+CommitDelivery
+├── StateInArgs         — full account data in instruction args
+├── StateInBuffer { stage } — data in on-chain buffer
+├── DiffInArgs { base_account } — diff against base in args
+└── DiffInBuffer { stage, base_account } — diff in buffer
+```
+
```
[the remark this answers is not in the document]
Comment (taco-paco) [reply magicblock-committor-service/CLAUDE.md]: removed file
